development: &default
  adapter: postgresql
  database: zaqueu_development
  #username: postgres
  encoding: utf8
  #password:
  host: localhost

test:
  <<: *default
  database: zaqueu_test

production:
  <<: *default
  database: zaqueu_production
